### ISSUE TITLE
INVALID_CLIENT: Invalid redirect URI

### ISSUE THREAD

**Issue by stoneobscurity** [pckhib/node-red-contrib-spotify#5]
getting this error when i try to auth.

also, how do i format the scope list? commas, json, semi-colons, what?

**Comment by k1ngf15h3r** [comment]
The Trick was to replace localhost with the Interface IP like "192.168.1.1" or whatever IP your Node-RED Host is listening on

**Comment by dumdiedum** [comment]
@k1ngf15h3r How exactly did you this? Just replacing the url http://localhost:1880 with http://192.168.x.x:1880 didn't fixed this error...

Is this a change in settings.js? Sorry, I'm a newb in node red.

**Comment by k1ngf15h3r** [comment]
@dumdiedum I changed this in the redirect URI in the Spotify Client ID Settings in the Developer dashboard. That was the only thing I changed. 

But for now I could not link the Spotify Node to my google cast node to play a playlist on it. Hope this will be possible in future updates

**Comment by dumdiedum** [comment]
yes, thx! I missed point 3 of the configuration guideline, this was my error.

**Comment by nortuzar** [comment]
Hi! I try everything but can't pass the INVALID_CLIENT: Invalid redirect URI
Try all the combinations on the Developer dashboard. All the combinations between ip/dns and http/https, 
https://xxxxxx.duckdns.org:1880/spotify-credentials/auth/callback
http://192.168.1.4:1880/spotify-credentials/auth/callback

Any clue? THANKS

**Comment by sniperxnl** [comment]
i have the same problem, any news?
